name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add Permission
      run: chmod +x ./gradlew
    - name: GoogleServiceJson
      env:
        GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON}}
      run: echo $GOOGLE_SERVICE | base64 --decode > ./app/google-services.json
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload apk file
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
